// AUTO-GENERATED by scripts/list-translated-properties.mjs. Do not edit by hand.
// Regenerated whenever a property is scaffolded for any locale, and on
// `npm run prebuild`.
//
// Source of truth: directory listing of content/docs/ja/properties/<slug>/.
// To add a slug: run `node scripts/scaffold-zh-property.mjs <slug> --lang=ja`
// (which also calls this script). To remove a slug: delete the directory and re-run.

export const JA_TRANSLATED_SLUGS: ReadonlySet<string> = new Set([
  '1-34-shotover',
  '10-15-gorge',
  '100-risinghurst-home',
  '100-risinghurst-unit',
  '10b-delamare',
  '2-34-shotover',
  '25-dublin',
  '3-15-gorge',
  '41-suburb-basecamp',
  '6-25-belfast',
  '6a-643-frankton',
  '7-suburb',
  '73a-hensman',
  '73b-hensman',
]);
