'use client';

import Link from 'next/link';
import { usePathname } from 'next/navigation';

/**
 * Locale switcher pill — EN · 中文 · 日本語. The current locale is rendered
 * muted; the others link to the equivalent path in their locale.
 *
 * The docs.snowbirdhq.com subdomain rewrites /:path → /docs/:path server-side,
 * so usePathname() returns either the un-prefixed form (most common on the
 * docs subdomain) or the /docs-prefixed form (rare, main domain). Both are
 * handled.
 *
 * Routes per locale:
 *   EN:  /properties/<slug>/...           or  /docs/properties/<slug>/...
 *   ZH:  /zh/properties/<slug>/...        or  /docs/zh/properties/<slug>/...
 *   JA:  /ja/properties/<slug>/...        or  /docs/ja/properties/<slug>/...
 *
 * For property-scoped paths, the link only points to the per-property page if
 * a translation exists for that locale; otherwise it falls back to the
 * locale-default property listing. The translated-slugs sets are
 * auto-regenerated by scripts/list-translated-properties.mjs (wired into
 * `npm run prebuild` and after every scaffold).
 */
import { ZH_TRANSLATED_SLUGS } from '@/lib/zh-properties';
import { JA_TRANSLATED_SLUGS } from '@/lib/ja-properties';

type LocaleId = 'en' | 'zh' | 'ja';

const LOCALE_ORDER: ReadonlyArray<LocaleId> = ['en', 'zh', 'ja'];

const LABELS: Record<LocaleId, string> = {
  en: 'EN',
  zh: '中文',
  ja: '日本語',
};

const TRANSLATED_BY_LOCALE: Record<LocaleId, ReadonlySet<string>> = {
  en: new Set(),
  zh: ZH_TRANSLATED_SLUGS,
  ja: JA_TRANSLATED_SLUGS,
};

export function LocaleSwitcher() {
  const pathname = usePathname() ?? '/';
  const current = detectLocale(pathname);

  return (
    <div
      className="not-prose"
      style={{
        display: 'inline-flex',
        alignItems: 'center',
        gap: '6px',
        whiteSpace: 'nowrap',
        fontFamily: 'var(--snow-font-mono)',
        fontSize: '12px',
        letterSpacing: '0.08em',
        background: 'var(--snow-paper)',
        border: '1px solid var(--snow-line)',
        borderRadius: '999px',
        padding: '4px 10px',
      }}
    >
      {LOCALE_ORDER.map((id, idx) => (
        <span key={id} style={{ display: 'inline-flex', alignItems: 'center', gap: '6px' }}>
          {idx > 0 && (
            <span style={{ color: 'var(--snow-line)' }} aria-hidden>
              ·
            </span>
          )}
          {id === current ? (
            <span style={{ color: 'var(--snow-ink-3)' }}>{LABELS[id]}</span>
          ) : (
            <Link
              href={localeHref(pathname, id)}
              style={{ color: 'var(--snow-accent)', textDecoration: 'none' }}
            >
              {LABELS[id]}
            </Link>
          )}
        </span>
      ))}
    </div>
  );
}

function detectLocale(path: string): LocaleId {
  for (const id of ['zh', 'ja'] as const) {
    if (
      path === `/${id}` ||
      path.startsWith(`/${id}/`) ||
      path === `/docs/${id}` ||
      path.startsWith(`/docs/${id}/`)
    ) {
      return id;
    }
  }
  return 'en';
}

/**
 * Compute the equivalent path in `target` locale. Strips any /docs prefix to
 * normalise, derives the property slug or queenstown-insights segment, and
 * re-emits with the target locale's prefix.
 */
function localeHref(path: string, target: LocaleId): string {
  const stripped = path.replace(/^\/docs/, '');
  const noLocale = stripLocale(stripped);

  // /properties/<slug>/...
  const propsMatch = noLocale.match(/^\/properties\/([^/]+)(\/.*)?$/);
  if (propsMatch) {
    const slug = propsMatch[1];
    const tail = propsMatch[2] ?? '';
    if (target === 'en') {
      return `/properties/${slug}${tail}`;
    }
    if (TRANSLATED_BY_LOCALE[target].has(slug)) {
      return `/docs/${target}/properties/${slug}${tail}`;
    }
    return `/docs/${target}`;
  }

  // /queenstown-insights or /queenstown-insights/...
  if (
    noLocale === '/queenstown-insights' ||
    noLocale.startsWith('/queenstown-insights/')
  ) {
    if (target === 'en') return `/docs${noLocale}`;
    return `/docs/${target}${noLocale}`;
  }

  // Default — locale root.
  if (target === 'en') return '/properties';
  return `/docs/${target}`;
}

function stripLocale(path: string): string {
  for (const id of ['zh', 'ja'] as const) {
    if (path === `/${id}`) return '/';
    if (path.startsWith(`/${id}/`)) return path.slice(id.length + 1);
  }
  return path;
}
