'use client';

import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { useEffect, useRef, useState } from 'react';

/**
 * Compact locale switcher — a small pill showing the current locale code
 * (EN / 中文 / 日本語) with a chevron. Clicking opens a dropdown with the
 * three locales; selecting one navigates to the equivalent path in that
 * locale or to the locale root if no per-property translation exists.
 *
 * Stripe-style compact pattern — small footprint suitable for the docs
 * nav header on every viewport. Current locale is shown at-a-glance;
 * the dropdown reveals the alternatives only when the user opts in.
 *
 * The translated-slugs sets are auto-regenerated by
 * scripts/list-translated-properties.mjs so the per-property links stay
 * accurate without hand-maintenance.
 */
import { ZH_TRANSLATED_SLUGS } from '@/lib/zh-properties';
import { JA_TRANSLATED_SLUGS } from '@/lib/ja-properties';

type LocaleId = 'en' | 'zh' | 'ja';

const LOCALE_ORDER: ReadonlyArray<LocaleId> = ['en', 'zh', 'ja'];

const LABELS: Record<LocaleId, string> = {
  en: 'EN',
  zh: '中文',
  ja: '日本語',
};

const TRANSLATED_BY_LOCALE: Record<LocaleId, ReadonlySet<string>> = {
  en: new Set(),
  zh: ZH_TRANSLATED_SLUGS,
  ja: JA_TRANSLATED_SLUGS,
};

export function LocaleSwitcher() {
  const pathname = usePathname() ?? '/';
  const current = detectLocale(pathname);
  const [open, setOpen] = useState(false);
  const wrapRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (!open) return;
    const onClick = (e: MouseEvent) => {
      if (!wrapRef.current?.contains(e.target as Node)) setOpen(false);
    };
    const onKey = (e: KeyboardEvent) => {
      if (e.key === 'Escape') setOpen(false);
    };
    document.addEventListener('mousedown', onClick);
    document.addEventListener('keydown', onKey);
    return () => {
      document.removeEventListener('mousedown', onClick);
      document.removeEventListener('keydown', onKey);
    };
  }, [open]);

  return (
    <div ref={wrapRef} className="not-prose relative">
      <button
        type="button"
        aria-haspopup="menu"
        aria-expanded={open}
        aria-label="Switch language"
        onClick={() => setOpen((v) => !v)}
        style={{
          display: 'inline-flex',
          alignItems: 'center',
          gap: '4px',
          fontFamily: 'var(--snow-font-mono)',
          fontSize: '12px',
          letterSpacing: '0.08em',
          background: 'var(--snow-paper)',
          border: '1px solid var(--snow-line)',
          borderRadius: '999px',
          padding: '3px 9px',
          color: 'var(--snow-ink)',
          cursor: 'pointer',
          whiteSpace: 'nowrap',
          lineHeight: 1.2,
        }}
      >
        <span>{LABELS[current]}</span>
        <span
          aria-hidden
          style={{
            fontSize: '9px',
            color: 'var(--snow-ink-3)',
            transform: open ? 'rotate(180deg)' : 'none',
            transition: 'transform 120ms ease',
          }}
        >
          ▾
        </span>
      </button>
      {open && (
        <div
          role="menu"
          aria-label="Language"
          style={{
            position: 'absolute',
            top: 'calc(100% + 6px)',
            right: 0,
            minWidth: '120px',
            background: 'var(--snow-paper)',
            border: '1px solid var(--snow-line)',
            borderRadius: '6px',
            boxShadow: '0 8px 24px rgba(0,0,0,0.08)',
            zIndex: 100,
            overflow: 'hidden',
            fontFamily: 'var(--snow-font-mono)',
            fontSize: '12px',
            letterSpacing: '0.08em',
          }}
        >
          {LOCALE_ORDER.map((id) => {
            const isCurrent = id === current;
            const inner = (
              <span
                style={{
                  display: 'inline-flex',
                  alignItems: 'center',
                  justifyContent: 'space-between',
                  width: '100%',
                }}
              >
                <span>{LABELS[id]}</span>
                {isCurrent && (
                  <span aria-hidden style={{ color: 'var(--snow-accent)' }}>
                    ✓
                  </span>
                )}
              </span>
            );
            const itemStyle = {
              display: 'block',
              padding: '8px 12px',
              textDecoration: 'none',
            } as const;
            if (isCurrent) {
              return (
                <span
                  key={id}
                  role="menuitem"
                  aria-current="true"
                  style={{
                    ...itemStyle,
                    color: 'var(--snow-ink-3)',
                    background: 'var(--snow-bg)',
                  }}
                >
                  {inner}
                </span>
              );
            }
            return (
              <Link
                key={id}
                href={localeHref(pathname, id)}
                role="menuitem"
                onClick={() => setOpen(false)}
                className="hover:bg-black/5"
                style={{ ...itemStyle, color: 'var(--snow-ink)' }}
              >
                {inner}
              </Link>
            );
          })}
        </div>
      )}
    </div>
  );
}

function detectLocale(path: string): LocaleId {
  for (const id of ['zh', 'ja'] as const) {
    if (
      path === `/${id}` ||
      path.startsWith(`/${id}/`) ||
      path === `/docs/${id}` ||
      path.startsWith(`/docs/${id}/`)
    ) {
      return id;
    }
  }
  return 'en';
}

/**
 * Compute the equivalent path in `target` locale. Strips any /docs prefix to
 * normalise, derives the property slug or queenstown-insights segment, and
 * re-emits with the target locale's prefix.
 */
function localeHref(path: string, target: LocaleId): string {
  const stripped = path.replace(/^\/docs/, '');
  const noLocale = stripLocale(stripped);

  // /properties/<slug>/...
  const propsMatch = noLocale.match(/^\/properties\/([^/]+)(\/.*)?$/);
  if (propsMatch) {
    const slug = propsMatch[1];
    const tail = propsMatch[2] ?? '';
    if (target === 'en') {
      return `/properties/${slug}${tail}`;
    }
    if (TRANSLATED_BY_LOCALE[target].has(slug)) {
      return `/docs/${target}/properties/${slug}${tail}`;
    }
    return `/docs/${target}`;
  }

  // /queenstown-insights or /queenstown-insights/...
  if (
    noLocale === '/queenstown-insights' ||
    noLocale.startsWith('/queenstown-insights/')
  ) {
    if (target === 'en') return `/docs${noLocale}`;
    return `/docs/${target}${noLocale}`;
  }

  // Default — locale root.
  if (target === 'en') return '/properties';
  return `/docs/${target}`;
}

function stripLocale(path: string): string {
  for (const id of ['zh', 'ja'] as const) {
    if (path === `/${id}`) return '/';
    if (path.startsWith(`/${id}/`)) return path.slice(id.length + 1);
  }
  return path;
}
